# Generated by Django 5.2.12 on 2026-04-12 00:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('document', models.CharField(max_length=20, unique=True, verbose_name='Documento de Identidad')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='Autoriza Tratamiento de Datos')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Contrasena')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SECRETARY', 'Secretaria'), ('STUDENT', 'Estudiante'), ('TEACHER', 'Profesor'), ('ADMIN', 'Administrador')], default='SECRETARY', max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('hour', models.CharField(choices=[('14:00', '14:00'), ('14:45', '14:45'), ('15:30', '15:30'), ('16:00', '16:00')], max_length=5, verbose_name='Hora')),
                ('type', models.CharField(choices=[('INPERSON', 'Presencial'), ('TELEPHONE', 'Telefonica'), ('VIRTUAL', 'Virtual')], default='INPERSON', max_length=20, verbose_name='Tipo de Cita')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('COMPLETED', 'Cumplida'), ('CANCELLED', 'Cancelada'), ('REASSIGNED', 'Reasignada'), ('ABSENCE', 'Inasistencia')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('attended', models.BooleanField(default=False, verbose_name='Asistio')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelacion/Inasistencia')),
                ('reason_type', models.CharField(choices=[('FIRST_TIME', 'Primera Vez'), ('CASE_FOLLOW_UP', 'Seguimiento de Caso')], default='FIRST_TIME', max_length=20, verbose_name='Tipo de Cita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultorio.beneficiary', verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EMAIL', 'Correo Electronico'), ('CALL', 'Llamada'), ('WHATSAPP', 'WhatsApp'), ('INTERNAL_CHAT', 'Chat Interno')], default='EMAIL', max_length=20, verbose_name='Tipo de Comunicacion')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripcion/Contenido')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='consultorio.appointment', verbose_name='Cita Relacionada')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='consultorio.beneficiary', verbose_name='Beneficiario')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Comunicacion',
                'verbose_name_plural': 'Comunicaciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('APPOINTMENT_SCHEDULED', 'Cita Agendada'), ('APPOINTMENT_CANCELLED', 'Cita Cancelada'), ('APPOINTMENT_REASSIGNED', 'Cita Reasignada'), ('CASE_ASSIGNED', 'Caso Asignado'), ('CASE_UPDATED', 'Caso Actualizado'), ('CASE_CLOSED', 'Caso Cerrado'), ('REQUIRED_DOCS', 'Documentos Requeridos'), ('RECORDED_ABSENCE', 'Inasistencia Registrada'), ('STUDENT_UNAVAILABLE', 'Estudiante No Disponible'), ('SCHEDULE_UPDATED', 'Agenda Actualizada')], max_length=30, verbose_name='Tipo de Evento')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('read', models.BooleanField(default=False, verbose_name='Leida')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='consultorio.beneficiary', verbose_name='Beneficiario')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_professional', models.CharField(max_length=50, unique=True, verbose_name='Matricula Profesional')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('reason_unavailability', models.TextField(blank=True, null=True, verbose_name='Razon de No Disponibilidad')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='student_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='consultorio.student', verbose_name='Estudiante Asignado'),
        ),
    ]
