# Generated by Django 5.2.12 on 2026-04-12 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_student_attendance_days_student_legal_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Sala Juridica',
                'verbose_name_plural': 'Salas Juridicas',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_generated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generacion')),
                ('period_start', models.DateField(verbose_name='Inicio del Periodo')),
                ('period_end', models.DateField(verbose_name='Fin del Periodo')),
                ('total_cases', models.IntegerField(default=0, verbose_name='Total de Casos')),
                ('active_cases', models.IntegerField(default=0, verbose_name='Casos Activos')),
                ('closed_cases', models.IntegerField(default=0, verbose_name='Casos Cerrados')),
                ('reassigned_cases', models.IntegerField(default=0, verbose_name='Casos Reasignados')),
                ('scheduled_appointments', models.IntegerField(default=0, verbose_name='Citas Agendadas')),
                ('attended_appointments', models.IntegerField(default=0, verbose_name='Citas Atendidas')),
                ('cancelled_appointments', models.IntegerField(default=0, verbose_name='Citas Canceladas')),
                ('beneficiary_absences', models.IntegerField(default=0, verbose_name='Inasistencias de Beneficiarios')),
                ('student_absences', models.IntegerField(default=0, verbose_name='Inasistencias de Estudiantes')),
                ('attendance_rate', models.FloatField(default=0.0, verbose_name='Tasa de Asistencia')),
                ('first_time_appointments', models.IntegerField(default=0, verbose_name='Citas Primera Vez')),
                ('follow_up_appointments', models.IntegerField(default=0, verbose_name='Citas de Seguimiento')),
            ],
            options={
                'verbose_name': 'Metrica',
                'verbose_name_plural': 'Metricas',
                'ordering': ['-date_generated'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendance_days',
        ),
        migrations.RemoveField(
            model_name='student',
            name='legal_office',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('description', models.TextField(verbose_name='Descripcion del Caso')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Asignado'), ('REJECTED', 'Rechazado'), ('INPROCESS', 'En Tramite'), ('COMPLETED', 'Finalizado'), ('CLOSE_FOR_ABSENCE', 'Cerrado por Inasistencia')], default='ASSIGNED', max_length=20, verbose_name='Estado')),
                ('absences_beneficiary', models.IntegerField(default=0, verbose_name='Inasistencias del Beneficiario')),
                ('reason_for_reassignment', models.TextField(blank=True, null=True, verbose_name='Razon de Reasignacion')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='consultorio.beneficiary', verbose_name='Beneficiario')),
                ('student_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='consultorio.student', verbose_name='Estudiante Asignado')),
                ('legal_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='consultorio.legalroom', verbose_name='Sala Juridica')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.AddField(
            model_name='communication',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='consultorio.case', verbose_name='Caso Relacionado'),
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('action', models.CharField(max_length=200, verbose_name='Accion')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consultorio.case', verbose_name='Caso')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultorio.student', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Historial del Caso',
                'verbose_name_plural': 'Historial de Casos',
                'ordering': ['-date'],
            },
        ),
    ]
