# Generated by Django 5.2.12 on 2026-04-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_legalroom_metrics_remove_student_attendance_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='consultorio.case', verbose_name='Caso Asociado'),
        ),
    ]
