# Generated by Django 5.2.12 on 2026-04-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0004_appointment_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='passwordVisible',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contrasena'),
        ),
    ]
