# Generated by Django 5.2.12 on 2026-04-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0005_beneficiary_passwordvisible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='passwordVisible',
        ),
    ]
